import { db } from "./db.js";
import {
  usersTable,
  tripsTable,
  itineraryDaysTable,
  activitiesTable,
  bookingsTable,
  expensesTable,
  expenseReportsTable,
  loyaltyAccountsTable,
  loyaltyTransactionsTable,
  rewardsTable,
  destinationsTable,
  hotelsTable,
  hotelRoomsTable,
  activityListingsTable,
  priceAlertsTable,
  notificationsTable,
  corporateTravelersTable,
  approvalsTable,
  travelPoliciesTable,
} from "@workspace/db";
import { eq } from "drizzle-orm";

export async function seedDatabase() {
  const existing = await db.select().from(usersTable).limit(1);
  if (existing.length > 0) return;

  const [user] = await db
    .insert(usersTable)
    .values({
      email: "alex.morgan@voyageai.com",
      firstName: "Alex",
      lastName: "Morgan",
      displayName: "Alex Morgan",
      nationality: "US",
      preferredCurrency: "USD",
      seatPreference: "window",
      mealPreference: "standard",
      role: "admin",
    })
    .returning();

  // Loyalty account
  await db.insert(loyaltyAccountsTable).values({
    userId: user.id,
    points: 84750,
    tier: "voyager",
    annualSpend: "18420.00",
    pointsExpiringSoon: 2500,
    expiryDate: "2025-06-30",
  });

  // Loyalty transactions
  await db.insert(loyaltyTransactionsTable).values([
    { userId: user.id, type: "earned", points: 2340, description: "Flight SFO → NRT — United Airlines", date: "2025-03-15", bookingRef: "UA-981422" },
    { userId: user.id, type: "earned", points: 1200, description: "Hotel — Park Hyatt Tokyo", date: "2025-03-16", bookingRef: "PH-33891" },
    { userId: user.id, type: "redeemed", points: -5000, description: "Redeemed: Airport lounge access (12 months)", date: "2025-03-01" },
    { userId: user.id, type: "earned", points: 890, description: "Flight CDG → LHR — Air France", date: "2025-02-14", bookingRef: "AF-12837" },
    { userId: user.id, type: "bonus", points: 3000, description: "Tier upgrade bonus — Voyager status achieved", date: "2025-01-01" },
  ]);

  // Rewards
  await db.insert(rewardsTable).values([
    { name: "Business Class Upgrade", description: "Upgrade any economy ticket to business class on long-haul flights", pointsCost: 25000, category: "flights", available: true },
    { name: "Free Hotel Night", description: "One free night at any partner hotel (up to $300 value)", pointsCost: 15000, category: "hotels", available: true },
    { name: "Airport Lounge Day Pass", description: "Access to 1,300+ airport lounges worldwide for one day", pointsCost: 3000, category: "experiences", available: true },
    { name: "Priority Boarding", description: "Priority boarding on your next 5 flights", pointsCost: 2000, category: "flights", available: true },
    { name: "Tokyo Experience Package", description: "3-night curated experience in Tokyo with guided tours", pointsCost: 50000, category: "experiences", available: true },
    { name: "Travel Insurance Upgrade", description: "Premium travel insurance for your next trip", pointsCost: 5000, category: "services", available: true },
  ]);

  // Destinations
  const [tokyo, paris, bali, nyc, dubai] = await db
    .insert(destinationsTable)
    .values([
      {
        name: "Tokyo",
        country: "Japan",
        slug: "tokyo-japan",
        imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
        tagline: "Where ancient tradition meets neon-lit future",
        description: "Tokyo is a city of infinite layers — from cherry blossom parks to Michelin-starred basement restaurants, from tranquil temples to buzzing Shibuya crossings.",
        avgFlightPrice: "980",
        avgHotelPrice: "180",
        bestMonths: ["March", "April", "October", "November"],
        tags: ["culture", "food", "technology", "nature"],
        highlights: ["Shibuya Crossing", "Senso-ji Temple", "Tsukiji Outer Market", "Akihabara", "Mount Fuji day trip"],
        weather: { spring: "15-22°C", summer: "27-35°C", autumn: "12-22°C", winter: "2-12°C" },
        visaInfo: "Visa-free for most nationalities up to 90 days",
        currency: "JPY",
        language: "Japanese",
        timezone: "JST (UTC+9)",
        dealScore: "8.9",
        isPopular: true,
      },
      {
        name: "Paris",
        country: "France",
        slug: "paris-france",
        imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        tagline: "The City of Light, romance, and world-class cuisine",
        description: "Paris rewards those who slow down — linger at a café, wander through the Marais, discover which arrondissement matches your mood.",
        avgFlightPrice: "720",
        avgHotelPrice: "210",
        bestMonths: ["April", "May", "September", "October"],
        tags: ["art", "romance", "food", "fashion"],
        highlights: ["Eiffel Tower", "Louvre Museum", "Montmartre", "Seine River Cruise", "Versailles"],
        weather: { spring: "11-20°C", summer: "20-28°C", autumn: "10-18°C", winter: "3-9°C" },
        visaInfo: "Schengen visa required for non-EU travelers",
        currency: "EUR",
        language: "French",
        timezone: "CET (UTC+1)",
        dealScore: "7.8",
        isPopular: true,
      },
      {
        name: "Bali",
        country: "Indonesia",
        slug: "bali-indonesia",
        imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
        tagline: "Emerald rice terraces, surf, and spiritual serenity",
        description: "Bali's magic lies in its contrasts — spiritual ceremonies at ancient temples, world-class surf breaks, and some of the best value luxury resorts on earth.",
        avgFlightPrice: "850",
        avgHotelPrice: "85",
        bestMonths: ["May", "June", "July", "August", "September"],
        tags: ["beach", "wellness", "surf", "culture", "budget-friendly"],
        highlights: ["Ubud Monkey Forest", "Tegallalang Rice Terraces", "Uluwatu Temple", "Seminyak Beach", "Mount Batur sunrise trek"],
        weather: { spring: "27-32°C", summer: "24-30°C", autumn: "26-31°C", winter: "26-31°C" },
        visaInfo: "Visa-on-arrival for most nationalities (30 days, extendable)",
        currency: "IDR",
        language: "Bahasa Indonesia / Balinese",
        timezone: "WITA (UTC+8)",
        dealScore: "9.2",
        isPopular: true,
      },
      {
        name: "New York City",
        country: "United States",
        slug: "new-york-city-us",
        imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
        tagline: "The city that never sleeps — and neither will you",
        description: "NYC moves at a pace that sharpens everything — the art is bolder, the food is better, and the energy is unlike anywhere else on the planet.",
        avgFlightPrice: "320",
        avgHotelPrice: "280",
        bestMonths: ["April", "May", "September", "October", "December"],
        tags: ["culture", "food", "shopping", "urban"],
        highlights: ["Central Park", "MoMA", "Brooklyn Bridge", "Broadway", "High Line"],
        weather: { spring: "10-22°C", summer: "25-35°C", autumn: "10-22°C", winter: "-5-5°C" },
        visaInfo: "ESTA for VWP countries; US visa for others",
        currency: "USD",
        language: "English",
        timezone: "ET (UTC-5)",
        dealScore: "7.5",
        isPopular: true,
      },
      {
        name: "Dubai",
        country: "UAE",
        slug: "dubai-uae",
        imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
        tagline: "Ambition made architecture — and the best airport in the world",
        description: "Dubai has reinvented itself as a global hub where superlatives are the baseline: the tallest building, the largest mall, the most ambitious culinary scene.",
        avgFlightPrice: "620",
        avgHotelPrice: "195",
        bestMonths: ["November", "December", "January", "February", "March"],
        tags: ["luxury", "shopping", "architecture", "desert"],
        highlights: ["Burj Khalifa", "The Dubai Mall", "Palm Jumeirah", "Dubai Frame", "Desert Safari"],
        weather: { spring: "25-38°C", summer: "38-45°C", autumn: "25-38°C", winter: "18-26°C" },
        visaInfo: "Visa-on-arrival for most nationalities (30 days)",
        currency: "AED",
        language: "Arabic / English",
        timezone: "GST (UTC+4)",
        dealScore: "8.1",
        isPopular: true,
      },
    ])
    .returning();

  // Hotels
  const [hotel1, hotel2, hotel3, hotel4, hotel5] = await db
    .insert(hotelsTable)
    .values([
      {
        name: "Park Hyatt Tokyo",
        destination: "Tokyo",
        address: "3-7-1-2 Nishi Shinjuku, Shinjuku-ku, Tokyo",
        stars: 5,
        reviewScore: "9.4",
        reviewCount: 3842,
        pricePerNight: "480",
        currency: "USD",
        imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
        amenities: ["Pool", "Spa", "Fitness Center", "Multiple Restaurants", "Bar", "Concierge", "Room Service"],
        freeCancellation: true,
        aiSummary: "Legendary high-rise luxury with the best views of Tokyo and Mount Fuji. Featured in Lost in Translation. The Peak Lounge on the 52nd floor is unmissable.",
        dealScore: "8.2",
        distanceFromCenter: "2.1",
        neighborhood: "Shinjuku",
        pros: ["Iconic views", "World-class spa", "Excellent service", "Great location"],
        cons: ["Premium pricing", "Some rooms are dated"],
      },
      {
        name: "Hotel De Crillon",
        destination: "Paris",
        address: "10 Place de la Concorde, 75008 Paris",
        stars: 5,
        reviewScore: "9.7",
        reviewCount: 1209,
        pricePerNight: "850",
        currency: "USD",
        imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
        amenities: ["Spa", "Pool", "Michelin Restaurant", "Concierge", "Butler Service", "Bar"],
        freeCancellation: false,
        aiSummary: "Probably Paris's finest palace hotel, facing Place de la Concorde. The Karl Lagerfeld suites are legendary. Exceptional for business stays requiring maximum prestige.",
        dealScore: "7.1",
        distanceFromCenter: "0.8",
        neighborhood: "8th Arrondissement",
        pros: ["Unbeatable location", "Exceptional service", "Historic grandeur", "Perfect concierge"],
        cons: ["Very expensive", "No pool", "Popular with tourists"],
      },
      {
        name: "Alaya Resort Ubud",
        destination: "Bali",
        address: "Jalan Hanoman, Ubud, Bali",
        stars: 4,
        reviewScore: "9.1",
        reviewCount: 2341,
        pricePerNight: "195",
        currency: "USD",
        imageUrl: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
        amenities: ["Infinity Pool", "Spa", "Yoga Classes", "Restaurant", "Free WiFi", "Free Breakfast"],
        freeCancellation: true,
        aiSummary: "Tucked into Ubud's jungle, Alaya delivers lush villa-style rooms at reasonable prices. The infinity pool overlooking the valley is postcard-perfect. Excellent F&B.",
        dealScore: "9.5",
        distanceFromCenter: "0.5",
        neighborhood: "Ubud Center",
        pros: ["Spectacular pool", "Great value", "Fantastic breakfast", "Central location"],
        cons: ["Busy area", "Can hear street noise"],
      },
      {
        name: "The Peninsula New York",
        destination: "New York City",
        address: "700 5th Ave, New York, NY 10019",
        stars: 5,
        reviewScore: "9.3",
        reviewCount: 4102,
        pricePerNight: "650",
        currency: "USD",
        imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c4a49f32?w=800",
        amenities: ["Rooftop Pool", "Spa", "Fitness Center", "Multiple Restaurants", "Rooftop Bar", "Concierge"],
        freeCancellation: true,
        aiSummary: "5th Avenue's most gracious grande dame. The rooftop bar has knockout Midtown views. Superior service and prime midtown location makes this the top choice for business travel.",
        dealScore: "8.4",
        distanceFromCenter: "0.0",
        neighborhood: "Midtown",
        pros: ["Prime 5th Ave location", "Rooftop terrace", "Impeccable service", "Beautiful rooms"],
        cons: ["Very expensive", "Busy area"],
      },
      {
        name: "Atlantis The Palm",
        destination: "Dubai",
        address: "Crescent Rd, Palm Jumeirah, Dubai",
        stars: 5,
        reviewScore: "8.6",
        reviewCount: 12483,
        pricePerNight: "380",
        currency: "USD",
        imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800",
        amenities: ["Private Beach", "Aquaventure Water Park", "Multiple Pools", "Casino", "20+ Restaurants", "Spa"],
        freeCancellation: false,
        aiSummary: "Dubai's most iconic resort — absurdly grand, with a water park, private beach, and 20+ restaurants. Best suited for families and those who want everything in one place.",
        dealScore: "8.8",
        distanceFromCenter: "8.2",
        neighborhood: "Palm Jumeirah",
        pros: ["Aquaventure included", "Private beach", "Everything on-site", "Spectacular design"],
        cons: ["Far from city center", "Very busy in peak season", "Can feel overwhelming"],
      },
    ])
    .returning();

  // Hotel rooms
  await db.insert(hotelRoomsTable).values([
    { hotelId: hotel1.id, name: "Deluxe City View", pricePerNight: "480", maxGuests: 2, bedType: "King", available: true },
    { hotelId: hotel1.id, name: "Park Suite", pricePerNight: "980", maxGuests: 3, bedType: "King + Sofa", available: true },
    { hotelId: hotel2.id, name: "Superior Room", pricePerNight: "850", maxGuests: 2, bedType: "King", available: true },
    { hotelId: hotel3.id, name: "Pool Villa", pricePerNight: "195", maxGuests: 2, bedType: "King", available: true },
    { hotelId: hotel4.id, name: "Superior Room", pricePerNight: "650", maxGuests: 2, bedType: "King", available: true },
    { hotelId: hotel5.id, name: "Ocean View King", pricePerNight: "380", maxGuests: 2, bedType: "King", available: true },
  ]);

  // Activity listings
  await db.insert(activityListingsTable).values([
    {
      name: "Senso-ji Temple Early Morning Walk",
      destination: "Tokyo",
      category: "culture",
      description: "Beat the crowds with a 6am private guide tour of Tokyo's most beloved temple. Includes traditional breakfast at a century-old teahouse.",
      price: "89",
      currency: "USD",
      duration: 180,
      reviewScore: "9.8",
      reviewCount: 847,
      imageUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800",
      bookInAdvance: true,
      groupSizeMin: 1,
      groupSizeMax: 8,
      tags: ["culture", "history", "early-morning", "photography"],
    },
    {
      name: "Tokyo Ramen Deep Dive",
      destination: "Tokyo",
      category: "food",
      description: "Visit 4 legendary ramen shops in one afternoon, from Sapporo-style miso to Tokyo shoyu. A true insider's tour with a local ramen obsessive.",
      price: "120",
      currency: "USD",
      duration: 240,
      reviewScore: "9.6",
      reviewCount: 1203,
      imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800",
      bookInAdvance: false,
      groupSizeMin: 2,
      groupSizeMax: 10,
      tags: ["food", "ramen", "local", "culinary"],
    },
    {
      name: "Ubud Sunrise Yoga & Ceremony",
      destination: "Bali",
      category: "wellness",
      description: "Start your day with sunrise yoga overlooking the Campuhan Ridge, followed by a Balinese blessing ceremony at a hidden temple.",
      price: "65",
      currency: "USD",
      duration: 150,
      reviewScore: "9.7",
      reviewCount: 2104,
      imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      bookInAdvance: true,
      groupSizeMin: 1,
      groupSizeMax: 15,
      tags: ["wellness", "yoga", "spiritual", "sunrise"],
    },
    {
      name: "Paris After Dark: Secret Bars & Jazz",
      destination: "Paris",
      category: "nightlife",
      description: "Three hidden cocktail bars that Parisians guard jealously, followed by a late-night jazz session in a cave-like Saint-Germain cellar.",
      price: "145",
      currency: "USD",
      duration: 270,
      reviewScore: "9.4",
      reviewCount: 512,
      imageUrl: "https://images.unsplash.com/photo-1514362448795-93d39e5c3ea4?w=800",
      bookInAdvance: true,
      groupSizeMin: 2,
      groupSizeMax: 12,
      tags: ["nightlife", "jazz", "cocktails", "hidden-gems"],
    },
    {
      name: "Dubai Desert Sundowner Safari",
      destination: "Dubai",
      category: "adventure",
      description: "Dune bashing in a 4x4, camel ride, sandboarding, and a gourmet dinner under the stars with live oud music. Dubai's best desert experience.",
      price: "175",
      currency: "USD",
      duration: 360,
      reviewScore: "9.2",
      reviewCount: 4521,
      imageUrl: "https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=800",
      bookInAdvance: false,
      groupSizeMin: 1,
      groupSizeMax: 20,
      tags: ["adventure", "desert", "cultural", "dinner"],
    },
  ]);

  // Trips
  const [trip1, trip2, trip3] = await db
    .insert(tripsTable)
    .values([
      {
        userId: user.id,
        name: "Cherry Blossom Japan",
        destination: "Tokyo, Japan",
        startDate: "2025-04-01",
        endDate: "2025-04-10",
        status: "upcoming",
        coverImageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
        totalBudget: "4500",
        totalSpent: "2840",
        travelers: 2,
        notes: "Focus on temples, ramen, and day trips to Nikko/Kamakura",
      },
      {
        userId: user.id,
        name: "Paris Business Sprint",
        destination: "Paris, France",
        startDate: "2025-02-14",
        endDate: "2025-02-17",
        status: "completed",
        coverImageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
        totalBudget: "2800",
        totalSpent: "2650",
        travelers: 1,
        notes: "Quarterly review + client dinners",
      },
      {
        userId: user.id,
        name: "Bali Recharge",
        destination: "Bali, Indonesia",
        startDate: "2025-06-10",
        endDate: "2025-06-17",
        status: "planning",
        coverImageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
        totalBudget: "3200",
        totalSpent: "0",
        travelers: 2,
        notes: "Ubud + Seminyak mix. No work.",
      },
    ])
    .returning();

  // Itinerary for Japan trip
  const [day1, day2, day3] = await db
    .insert(itineraryDaysTable)
    .values([
      { tripId: trip1.id, dayNumber: 1, date: "2025-04-01", title: "Arrival & Shinjuku", estimatedCost: "180" },
      { tripId: trip1.id, dayNumber: 2, date: "2025-04-02", title: "Asakusa & Ueno", estimatedCost: "220" },
      { tripId: trip1.id, dayNumber: 3, date: "2025-04-03", title: "Shibuya & Harajuku", estimatedCost: "195" },
    ])
    .returning();

  await db.insert(activitiesTable).values([
    {
      tripId: trip1.id,
      dayId: day1.id,
      timeSlot: "afternoon",
      name: "Check in at Park Hyatt",
      description: "Check into hotel, refresh, explore hotel facilities",
      location: "Park Hyatt Tokyo, Shinjuku",
      estimatedCost: "0",
      duration: 60,
      category: "accommodation",
      isBooked: true,
      sortOrder: 1,
    },
    {
      tripId: trip1.id,
      dayId: day1.id,
      timeSlot: "evening",
      name: "Omoide Yokocho (Memory Lane)",
      description: "Tiny alley packed with yakitori and sake bars. Best introduction to Tokyo street food culture.",
      location: "Shinjuku, Tokyo",
      estimatedCost: "45",
      duration: 90,
      category: "food",
      isBooked: false,
      sortOrder: 2,
    },
    {
      tripId: trip1.id,
      dayId: day2.id,
      timeSlot: "morning",
      name: "Senso-ji Temple at dawn",
      description: "Arrive by 6am to avoid the crowds. Walk the Nakamise-dori shopping street.",
      location: "Asakusa, Tokyo",
      estimatedCost: "0",
      duration: 120,
      category: "culture",
      isBooked: false,
      tips: "Exit the train at Asakusa Station on the Toei Asakusa line",
      sortOrder: 3,
    },
    {
      tripId: trip1.id,
      dayId: day3.id,
      timeSlot: "morning",
      name: "Meiji Shrine",
      description: "Start with the forested sanctuary of Meiji Shrine, then walk to Harajuku's Takeshita Street.",
      location: "Harajuku, Tokyo",
      estimatedCost: "10",
      duration: 90,
      category: "culture",
      isBooked: false,
      sortOrder: 4,
    },
    {
      tripId: trip1.id,
      dayId: day3.id,
      timeSlot: "evening",
      name: "Shibuya Crossing at night",
      description: "Watch the world's busiest pedestrian crossing from Starbucks or the Mag's Park rooftop.",
      location: "Shibuya, Tokyo",
      estimatedCost: "0",
      duration: 45,
      category: "sightseeing",
      isBooked: false,
      sortOrder: 5,
    },
  ]);

  // Bookings
  await db.insert(bookingsTable).values([
    {
      userId: user.id,
      tripId: trip1.id,
      type: "flight",
      status: "confirmed",
      reference: "UA-981422",
      providerName: "United Airlines",
      description: "SFO → NRT — Economy",
      startDate: "2025-04-01",
      endDate: "2025-04-02",
      amount: "980",
      currency: "USD",
      passengerCount: 2,
      isRefundable: false,
      metadata: { origin: "SFO", destination: "NRT", flightNumber: "UA837", seatNumbers: "24A, 24B", hotelAddress: null, confirmationDetails: null },
    },
    {
      userId: user.id,
      tripId: trip1.id,
      type: "hotel",
      status: "confirmed",
      reference: "PH-33891",
      providerName: "Park Hyatt Tokyo",
      description: "Deluxe City View — 9 nights",
      startDate: "2025-04-01",
      endDate: "2025-04-10",
      amount: "4320",
      currency: "USD",
      passengerCount: 2,
      isRefundable: true,
      metadata: { origin: null, destination: null, flightNumber: null, seatNumbers: null, hotelAddress: "3-7-1-2 Nishi Shinjuku, Shinjuku-ku", confirmationDetails: "Breakfast included" },
    },
    {
      userId: user.id,
      tripId: trip2.id,
      type: "flight",
      status: "confirmed",
      reference: "AF-12837",
      providerName: "Air France",
      description: "SFO → CDG — Business",
      startDate: "2025-02-14",
      endDate: "2025-02-14",
      amount: "2140",
      currency: "USD",
      passengerCount: 1,
      isRefundable: false,
      metadata: { origin: "SFO", destination: "CDG", flightNumber: "AF65", seatNumbers: "2A", hotelAddress: null, confirmationDetails: null },
    },
  ]);

  // Expenses
  await db.insert(expensesTable).values([
    { userId: user.id, tripId: trip2.id, category: "accommodation", description: "Hotel de Crillon — 3 nights", amount: "2550", amountUsd: "2550", currency: "USD", date: "2025-02-14", merchant: "Hotel de Crillon", status: "approved" },
    { userId: user.id, tripId: trip2.id, category: "meals", description: "Client dinner — Septime", amount: "420", amountUsd: "420", currency: "USD", date: "2025-02-15", merchant: "Septime Restaurant", status: "approved" },
    { userId: user.id, tripId: trip2.id, category: "transport", description: "CDG → Hotel taxi", amount: "85", amountUsd: "85", currency: "USD", date: "2025-02-14", merchant: "G7 Taxi", status: "approved" },
    { userId: user.id, category: "meals", description: "Team lunch at Bix", amount: "189", amountUsd: "189", currency: "USD", date: "2025-03-20", merchant: "Bix Restaurant", status: "pending" },
    { userId: user.id, category: "transport", description: "Uber — Client office to SFO", amount: "47", amountUsd: "47", currency: "USD", date: "2025-03-18", merchant: "Uber", status: "pending" },
  ]);

  // Expense report
  const [report] = await db.insert(expenseReportsTable).values({
    userId: user.id,
    tripId: trip2.id,
    title: "Paris Q1 Business Trip",
    status: "approved",
    totalAmount: "3055",
    currency: "USD",
    expenseCount: 3,
    submittedAt: "2025-02-20",
    approvedAt: "2025-02-24",
  }).returning();

  // Price alerts
  await db.insert(priceAlertsTable).values([
    {
      userId: user.id,
      type: "flight",
      label: "SFO → NRT (April 2025)",
      currentPrice: "892",
      targetPrice: "750",
      priceChange: "-88",
      priceChangePercent: "-8.97",
      triggered: false,
      active: true,
    },
    {
      userId: user.id,
      type: "hotel",
      label: "Bali — Alaya Ubud (June 10-17)",
      currentPrice: "175",
      targetPrice: "150",
      priceChange: "20",
      priceChangePercent: "12.9",
      triggered: false,
      active: true,
    },
    {
      userId: user.id,
      type: "flight",
      label: "SFO → DXB (November 2025)",
      currentPrice: "645",
      targetPrice: "600",
      priceChange: "-55",
      priceChangePercent: "-7.87",
      triggered: true,
      active: false,
    },
  ]);

  // Notifications
  await db.insert(notificationsTable).values([
    {
      userId: user.id,
      type: "price_alert",
      title: "Price drop detected",
      message: "SFO → DXB flights dropped to $645 — your target was $600, very close! Check availability now.",
      isRead: false,
      priority: "high",
      actionUrl: "/alerts",
      actionLabel: "View Alert",
    },
    {
      userId: user.id,
      type: "trip_reminder",
      title: "Japan trip in 18 days",
      message: "Your Cherry Blossom Japan trip starts April 1. You still have 2 activities unbooked — want to confirm them?",
      isRead: false,
      priority: "medium",
      actionUrl: "/trips/1",
      actionLabel: "View Trip",
    },
    {
      userId: user.id,
      type: "loyalty",
      title: "Points expiring soon",
      message: "2,500 loyalty points expire June 30. Redeem them before they vanish — check the rewards catalog.",
      isRead: false,
      priority: "medium",
      actionUrl: "/loyalty",
      actionLabel: "Redeem Points",
    },
    {
      userId: user.id,
      type: "expense",
      title: "Expense report approved",
      message: "Your Paris Q1 Business Trip expense report ($3,055) has been approved. Payment in 5-7 business days.",
      isRead: true,
      priority: "low",
      actionUrl: "/expenses",
      actionLabel: "View Report",
    },
  ]);

  // Corporate travelers
  await db.insert(corporateTravelersTable).values([
    { userId: user.id, name: "Alex Morgan", email: "alex.morgan@voyageai.com", department: "Executive", role: "CEO", totalSpend: "18420", tripsCount: 14, complianceRate: "97.5", currentLocation: "San Francisco, CA", status: "traveling" },
    { name: "Sarah Chen", email: "sarah.chen@voyageai.com", department: "Engineering", role: "VP Engineering", totalSpend: "12340", tripsCount: 9, complianceRate: "100", currentLocation: "Remote", status: "idle" },
    { name: "Marcus Williams", email: "marcus.w@voyageai.com", department: "Sales", role: "Account Executive", totalSpend: "23100", tripsCount: 22, complianceRate: "88.2", currentLocation: "New York, NY", status: "traveling" },
    { name: "Elena Petrov", email: "elena.p@voyageai.com", department: "Marketing", role: "CMO", totalSpend: "8920", tripsCount: 7, complianceRate: "95.0", currentLocation: "London, UK", status: "traveling" },
    { name: "James Okafor", email: "james.o@voyageai.com", department: "Finance", role: "CFO", totalSpend: "6200", tripsCount: 5, complianceRate: "100", status: "idle" },
  ]);

  // Approvals
  await db.insert(approvalsTable).values([
    {
      travelerName: "Marcus Williams",
      travelerEmail: "marcus.w@voyageai.com",
      department: "Sales",
      tripDescription: "Enterprise client summit — NYC",
      destination: "New York, NY",
      travelDates: "Apr 15-18, 2025",
      totalAmount: "2840",
      currency: "USD",
      status: "pending",
      submittedAt: "2025-03-22",
      policyCompliant: false,
      policyNotes: "Hotel rate ($380/night) exceeds policy max of $250/night",
    },
    {
      travelerName: "Elena Petrov",
      travelerEmail: "elena.p@voyageai.com",
      department: "Marketing",
      tripDescription: "Cannes Lions Festival — speaker engagements",
      destination: "Cannes, France",
      travelDates: "Jun 16-21, 2025",
      totalAmount: "4200",
      currency: "USD",
      status: "pending",
      submittedAt: "2025-03-25",
      policyCompliant: true,
      policyNotes: null,
    },
    {
      travelerName: "Sarah Chen",
      travelerEmail: "sarah.chen@voyageai.com",
      department: "Engineering",
      tripDescription: "AWS re:Invent conference",
      destination: "Las Vegas, NV",
      travelDates: "Dec 1-6, 2025",
      totalAmount: "1890",
      currency: "USD",
      status: "approved",
      submittedAt: "2025-03-10",
      reviewedAt: "2025-03-12",
      policyCompliant: true,
    },
  ]);

  // Travel policy
  await db.insert(travelPoliciesTable).values({
    companyId: 1,
    maxHotelRatePerNight: "250",
    maxFlightClassShortHaul: "economy",
    maxFlightClassLongHaul: "business",
    advanceBookingDays: 7,
    requiresApprovalAbove: "1500",
    perDiemRate: "75",
    currency: "USD",
    preferredAirlines: ["United Airlines", "Delta", "American Airlines", "Singapore Airlines"],
    preferredHotelChains: ["Hyatt", "Marriott", "Hilton", "IHG"],
  });

  console.log("Database seeded successfully");
}
